#!/usr/bin/env ruby

require 'japanese/train/access'
require 'thor'

module JapaneseTrainAccess
  class CLI < Thor

    default_task :jta
    desc "jta", "If you want to seach train access information in japan near by now time."
    def jta
      Japanese::Train::Access.route
    end

    desc "version", "version"
    def version
      p Japanese::Train::Access::VERSION
    end
  end
end

JapaneseTrainAccess::CLI.start(ARGV)
